module.exports = {
  'primary-color': '#5aaafa',
  'link-color': '#5aaafa',
  'border-radius-base': '2px',
  'layout-body-background': '#1E1E1E',
  'body-background': '#1E1E1E',
  'background-color-base': '#fcfff6',
  'layout-sider-background': '#272d33',
  'component-background': '#2E2E2E',
  'input-bg': '#fff',
  'btn-default-bg': '#8c9ba5',
  'btn-primary-color': '#2E2E2E',
  'heading-color': 'fade(#fff, 85%)',
  'tooltip-bg': '#152935',
  'border-color-base': '#152935',
  'border-color-split': '#152935',
  'text-color': 'fade(#fff, 100%)',
  'text-color-secondary': 'fade(#dfe6eb, 100%)',
  'success-color': '#8cd211',
  'error-color': '#ff5050',
  'warning-color': '#efc100',
  'info-color': '#7cc7ff',
  'highlight-color': '#ff5050',
  'background-color-light': '#8c9ba5',
  'processing-color': '#7cc7ff',
  'table-header-bg': '#1E1E1E',
  'table-row-hover-bg': 'fade(#7cc7ff, 70%)',
  'table-selected-row-bg': 'fade(#7cc7ff, 70%)',
  'item-hover-bg': '#7cc7ff',
  'item-active-bg': '#7cc7ff',
  'input-color': '#585558',
  'alert-message-color': '#1E1E1E',
  'alert-text-color': '#152935',
  'alert-close-color': '#152935',
  'table-expanded-row-bg': '#1E1E1E',
  'font-size-base': '16px',
};
